# DRIVESMART — Phase 2: Data Understanding & EDA

In [4]:
# ─────────────────────────────────────────────
# DRIVESMART — Phase 2: Data Understanding & EDA
# Step 1: Import Libraries & Load Data
# ─────────────────────────────────────────────

# Core
import pandas as pd
import numpy as np
from pathlib import Path

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

plt.rcParams['figure.figsize'] = (12, 5)
plt.rcParams['axes.spines.top']   = False
plt.rcParams['axes.spines.right'] = False

# ─────────────────────────────────────────────
# Load data
# ─────────────────────────────────────────────

DATA_DIR = Path('/Users/rupeshmaadas/Documents/Projects/Drivesmart/kayak_data')

df = pd.read_csv(DATA_DIR / 'kayak_San_Jose_20260322_to_20260323_20260316_013841.csv')

# ─────────────────────────────────────────────
# Quick sanity check
# ─────────────────────────────────────────────

print("Shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())
print("\nFirst 5 rows:")
df.head()

Shape: (638, 8)

Column names:
['Name', 'Name_Element', 'Location', 'Price', 'Provider', 'Start_Date', 'End_Date', 'Extraction_Date']

First 5 rows:

,Name,Name_Element,Location,Price,Provider,Start_Date,End_Date,Extraction_Date
0,Toyota Corolla,or similar Intermediate,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23,2026-03-16 01:37:58
1,Toyota Corolla,or similar Intermediate,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23,2026-03-16 01:37:58
2,Hyundai Accent,or similar Economy,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23,2026-03-16 01:37:58
3,Hyundai Accent,or similar Economy,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23,2026-03-16 01:37:58
4,Nissan Versa,or similar Compact,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23,2026-03-16 01:37:58

Step 2: Data Understanding

In [6]:

# ── 2.1 Data types ───────────────────────────
print("=" * 50)
print("DATA TYPES")
print("=" * 50)
print(df.dtypes)

# ── 2.2 Missing values ───────────────────────
print("\n" + "=" * 50)
print("MISSING VALUES")
print("=" * 50)
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
print(pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct}))

# ── 2.3 Duplicates ───────────────────────────
print("\n" + "=" * 50)
print("DUPLICATES")
print("=" * 50)
print(f"Total duplicate rows : {df.duplicated().sum()}")
print(f"Unique rows          : {df.shape[0] - df.duplicated().sum()}")

# ── 2.4 Unique values per column ─────────────
print("\n" + "=" * 50)
print("UNIQUE VALUES PER COLUMN")
print("=" * 50)
for col in df.columns:
    print(f"{col:<20} {df[col].nunique():>5} unique values")

# ── 2.5 Sample values per column ─────────────
print("\n" + "=" * 50)
print("SAMPLE VALUES PER COLUMN")
print("=" * 50)
for col in df.columns:
    samples = df[col].dropna().unique()[:4]
    print(f"\n{col}:")
    for s in samples:
        print(f"   → {s}")

==================================================
DATA TYPES
==================================================
Name               object
Name_Element       object
Location           object
Price              object
Provider           object
Start_Date         object
End_Date           object
Extraction_Date    object
dtype: object

==================================================
MISSING VALUES
==================================================
                 Missing Count  Missing %
Name                         0       0.00
Name_Element                 0       0.00
Location                     0       0.00
Price                        0       0.00
Provider                     0       0.00
Start_Date                   0       0.00
End_Date                     0       0.00
Extraction_Date              0       0.00

==================================================
DUPLICATES
==================================================
Total duplicate rows : 297
Unique rows          : 341

==================================================
UNIQUE VALUES PER COLUMN
==================================================
Name                   121 unique values
Name_Element            26 unique values
Location                42 unique values
Price                  127 unique values
Provider                28 unique values
Start_Date               1 unique values
End_Date                 1 unique values
Extraction_Date         44 unique values

==================================================
SAMPLE VALUES PER COLUMN
==================================================

Name:
   → Toyota Corolla
   → Hyundai Accent
   → Nissan Versa
   → Toyota RAV4

Name_Element:
   → or similar Intermediate
   → or similar Economy
   → or similar Compact
   → or similar Intermediate SUV

Location:
   → SJC: San Jose
Shuttle
   → SJC: San Jose
Airport terminal
   → SJC: San Jose
Call for pick-up
   → 3591 Pearl Avenue, San Jose
4.4 mi from city center

Price:
   → $44
   → $62
   → $68
   → $77

Provider:
   → Car agency: Payless
   → Car agency: Sixt
   → Car agency: Dollar
   → Car agency: Hertz

Start_Date:
   → 2026-03-22

End_Date:
   → 2026-03-23

Extraction_Date:
   → 2026-03-16 01:37:58
   → 2026-03-16 01:37:59
   → 2026-03-16 01:38:00
   → 2026-03-16 01:38:01

In [35]:
# ── Drop Extraction_Date ─────────────────
df.drop(columns=['Extraction_Date'], inplace=True)
print("Extraction_Date dropped ✓")
print(f"Columns remaining: {df.columns.tolist()}")

Extraction_Date dropped ✓
Columns remaining: ['Name', 'Name_Element', 'Location', 'Price', 'Provider', 'Start_Date', 'End_Date']

In [37]:
df.head()

,Name,Name_Element,Location,Price,Provider,Start_Date,End_Date
0,Toyota Corolla,or similar Intermediate,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23
1,Toyota Corolla,or similar Intermediate,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23
2,Hyundai Accent,or similar Economy,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23
3,Hyundai Accent,or similar Economy,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23
4,Nissan Versa,or similar Compact,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23

In [39]:
# ── Clean Name_Element ───────────────────────
df['Name_Element'] = df['Name_Element'].str.replace('or similar ', '', regex=False).str.strip()
print("'or similar' removed from Name_Element ✓")
print(df['Name_Element'].value_counts().to_string())

'or similar' removed from Name_Element ✓
Name_Element
5 stars5.0 vehicle score                              132
5 stars4.9 vehicle score                               46
View deal for more details.                            46
Minivan                                                30
Intermediate                                           28
Standard                                               28
Compact                                                28
Passenger van                                          28
Standard SUV                                           26
Economy                                                26
Book and save. Vehicle size determined at pick-up.     24
Full-size                                              24
Full-size SUV                                          24
Compact SUV                                            22
Premium SUV                                            22
Luxury                                                 20
Intermediate SUV                                       20
Pickup truck                                           18
Premium                                                14
Luxury SUV                                             12
5 stars4.8 vehicle score                                6
Convertible                                             6
Open air all terrain                                    2
4 stars3.5 vehicle score                                2
5 stars4.6 vehicle score                                2
Premium coupe                                           2

In [41]:
df.head()

,Name,Name_Element,Location,Price,Provider,Start_Date,End_Date
0,Toyota Corolla,Intermediate,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23
1,Toyota Corolla,Intermediate,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23
2,Hyundai Accent,Economy,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23
3,Hyundai Accent,Economy,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23
4,Nissan Versa,Compact,SJC: San Jose\nShuttle,$44,Car agency: Payless,2026-03-22,2026-03-23